### ISSUE TITLE
Reduced pci-virtio-block performance

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/propolis#518]
With #504 I've noticed that the unpacking stage of `apt dist-upgrade` on a Debian guest is taking around 30 minutes. On the same image with #504 reverted, the unpacking stage takes around 1 minute. I am using file-backed storage underpinned by a zvol.

```toml
[dev.block0]
driver = "pci-virtio-block"
block_dev = "main_disk"
pci-path = "0.4.0"

[block_dev.main_disk]
type = "file"
path = "/dev/zvol/dsk/rpool/falcon/topo/bgplower/sw0"
```

The host disk is a Samsung EVO 970 2TB NVMe with trim enabled in ZFS.
