### ISSUE TITLE
cannot have two file-backed block devices

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/propolis#59]
With this configuration file, for `propolis-standalone`:

```toml
[main]
name = "build0"
cpus = 8
bootrom = "/ws/vm/OVMF_CODE.fd"
memory = 8192

[block_dev.zvol]
type = "file"
path = "/dev/zvol/rdsk/rpool/data/vm/build0/disk0"

[block_dev.cpio]
type = "file"
path = "/dev/zvol/rdsk/rpool/data/vm/build0/disk1"

[dev.block0]
driver = "pci-virtio-block"
block_dev = "zvol"
pci-path = "0.4.0"

[dev.block1]
driver = "pci-virtio-block"
block_dev = "cpio"
pci-path = "0.5.0"

[dev.net0]
driver = "pci-virtio-viona"
vnic = "build0"
pci-path = "0.6.0"
```

The program crashes very early:

```
$ RUST_BACKTRACE=1 pfexec ./target/debug/propolis-standalone stand.toml
vm build0 created
Couldn't bind to ./ttya, removing and trying again...
thread 'main' panicked at 'assertion failed: res.is_none()', propolis/src/dispatch/sync_tasks.rs:127:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8f2463c68a6532d74a13ec402ec5b513e4e2726/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/a8f2463c68a6532d74a13ec402ec5b513e4e2726/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/a8f2463c68a6532d74a13ec402ec5b513e4e2726/library/core/src/panicking.rs:50:5
   3: propolis::dispatch::sync_tasks::SyncDispatch::spawn
             at ./propolis/src/dispatch/sync_tasks.rs:127:9
   4: propolis::dispatch::Dispatcher::spawn_sync
             at ./propolis/src/dispatch/mod.rs:84:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Abort
```

With a small change, I can see what the problem is:

```diff
diff --git a/propolis/src/dispatch/sync_tasks.rs b/propolis/src/dispatch/sync_tasks.rs
index 59d7166..d20fe37 100644
--- a/propolis/src/dispatch/sync_tasks.rs
+++ b/propolis/src/dispatch/sync_tasks.rs
@@ -121,10 +121,10 @@ impl SyncDispatch {
         })?;

         let res = inner.workers.insert(
-            Ident::Custom(name),
+            Ident::Custom(name.clone()),
             Detail { join: Some(hdl), ctrl, wake },
         );
-        assert!(res.is_none());
+        assert!(res.is_none(), "duplicate worker name: {:?}", name);

         Ok(())
     }
```

```
$ pfexec ./target/debug/propolis-standalone stand.toml
vm build0 created
Couldn't bind to ./ttya, removing and trying again...
thread 'main' panicked at 'duplicate worker name: "file bdev worker 0"', propolis/src/dispatch/sync_tasks.rs:127:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort
```

It seems like every file blockdev ends up creating threads with the same name?  If I change it to include the fd of the backing file, the VM starts OK:

```diff
diff --git a/propolis/src/block/file.rs b/propolis/src/block/file.rs
index d5aaf10..1c2b51f 100644
--- a/propolis/src/block/file.rs
+++ b/propolis/src/block/file.rs
@@ -168,7 +168,11 @@ impl Driver {

             let _ = disp
                 .spawn_sync(
-                    format!("file bdev worker {}", i),
+                    format!(
+                        "file bdev fd {} worker {}",
+                        self.fp.as_raw_fd(),
+                        i,
+                    ),
                     Box::new(move |mut sctx| {
                         tself.blocking_loop(&mut sctx);
                     }),
```

```
$ pfexec ./target/debug/propolis-standalone stand.toml
vm build0 created
Couldn't bind to ./ttya, removing and trying again...
- 1: chipset
  - 2: com1
  - 3: com2
  - 4: com3
  - 5: com4
  - 6: ps2_ctrl
  - 13: fwcfg
  - 14: ramfb
- 7: debug
- 8: vioblk-block0
  - 9: backend-file
- 10: vioblk-block1
  - 11: backend-file
- 12: viona-net0
Waiting for a connection to ttya...
```

I'm not sure what the right ID to use is, or if this is even the right strategy here.
