### ISSUE TITLE
Confusing message from `propolis-standalone` when VNIC is missing

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/propolis#612]
I included the following VNIC in my `propolis-standalone` TOML file, but forgot to create the VNIC:
```toml
[dev.net0]
driver = "pci-virtio-viona"
vnic = "vnic_prop0"
pci-path = "0.6.0"
```

When running `propolis-standalone`, it unceremoniously exits with
```
Error: DLADM_STATUS_NOTFOUND
```

Having a more informative error message would be appreciated!
